# uninstall.yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: automation-broker-apb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation-broker-apb
  namespace: automation-broker-apb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: automation-broker-apb
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: automation-broker-apb
  namespace: automation-broker-apb
---
apiVersion: v1
kind: Pod
metadata:
  generateName: automation-broker-apb
  namespace: automation-broker-apb
spec:
  serviceAccount: automation-broker-apb
  restartPolicy: Never
  containers:
    - name: apb
      image: 'automationbroker/automation-broker-apb:depro'
      args: [ "deprovision", "--extra-vars", '{ "broker_image": "docker.io/ansibleplaybookbundle/origin-ansible-service-broker", "broker_namespace": "eriks-cluster-broker", "create_broker_namespace": true }' ]
      imagePullPolicy: IfNotPresent
