apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
  namespace: automation-broker
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - automationbroker.io
  resourceNames:
  - e57ccbce-c718-11e8-b62b-0242ac110005
  resources:
  - bundlebindings
  verbs:
  - delete
- apiGroups:
  - automationbroker.io
  resources:
  - bundlebindings
  verbs:
  - create
  - get
- apiGroups:
  - automationbroker.io
  resources:
  - bundleinstances
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automationbroker.io
  resources:
  - bundles
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
  namespace: foo
rules:
- apiGroups:
  - ""
  resourceNames:
  - foo
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
  namespace: automation-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
subjects:
- kind: ServiceAccount
  name: automation-broker
  namespace: automation-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
subjects:
- kind: ServiceAccount
  name: automation-broker
  namespace: automation-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.6.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-automation-broker-automation-broker
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: audit2rbac:system:serviceaccount:automation-broker:automation-broker
subjects:
- kind: ServiceAccount
  name: automation-broker
  namespace: automation-broker
